"""
Week 06 INDIVIDUAL ASSIGNMENT -- Patch Compliance Audit
ITIA 1510 Cybersecurity Automation

Tests for the functions in patch_audit.py. Do not edit this file.

Run it from the folder that holds patch_audit.py:

    python -m unittest test_patch_audit -v

Some tests pass before you start, because a placeholder happens to return the
right answer for that one case. A green test is only worth something once you
have written the function.

Every test has a comment above it saying what it checks. When one fails, read
that comment first.

The report TODOs, 8 through 10, are not tested here. Check those against the
table in the assignment.
"""

import unittest

try:
    import patch_audit as pa
except ModuleNotFoundError:
    # the instructor copy of the program keeps its week06_ name
    import week06_individual_patch_audit as pa


class TestPatchLimit(unittest.TestCase):
    """TODO 1: patch_limit."""

    # Criticality 3 is the domain controllers and databases: 14 days.
    def test_criticality_3_gets_14_days(self) -> None:
        self.assertEqual(pa.patch_limit(3), 14)

    # Criticality 2 is the servers: 30 days.
    def test_criticality_2_gets_30_days(self) -> None:
        self.assertEqual(pa.patch_limit(2), 30)

    # Criticality 1 is the workstations and kiosks: 60 days.
    def test_criticality_1_gets_60_days(self) -> None:
        self.assertEqual(pa.patch_limit(1), 60)


class TestPatchStatus(unittest.TestCase):
    """TODO 2: patch_status."""

    # 9 days against a 14 day limit is inside the policy.
    def test_inside_the_limit_is_compliant(self) -> None:
        self.assertEqual(pa.patch_status("dc-01", 9, 3, []), "COMPLIANT")

    # Exactly on the limit still counts as compliant.
    def test_exactly_on_the_limit_is_compliant(self) -> None:
        self.assertEqual(pa.patch_status("mail-01", 30, 2, []), "COMPLIANT")

    # One day past a 60 day limit.
    def test_one_day_past_the_limit_is_overdue(self) -> None:
        self.assertEqual(pa.patch_status("file-01", 61, 1, []), "OVERDUE")

    # Exactly twice the limit is still OVERDUE, not CRITICAL.
    def test_exactly_twice_the_limit_is_overdue(self) -> None:
        self.assertEqual(pa.patch_status("web-02", 60, 2, []), "OVERDUE")

    # 95 days is more than twice a 14 day limit.
    def test_past_twice_the_limit_is_critical(self) -> None:
        self.assertEqual(pa.patch_status("db-01", 95, 3, []), "CRITICAL")

    # A host on the exception list is EXEMPT, even with terrible numbers.
    # Check EXEMPT before anything else.
    def test_exempt_beats_critical(self) -> None:
        self.assertEqual(pa.patch_status("lab-sandbox-01", 400, 1, ["lab-sandbox-01"]), "EXEMPT")

    # An exempt host with good numbers is still EXEMPT, not COMPLIANT.
    def test_exempt_beats_compliant(self) -> None:
        self.assertEqual(pa.patch_status("lab-sandbox-02", 5, 1, ["lab-sandbox-02"]), "EXEMPT")


class TestDaysOverdue(unittest.TestCase):
    """TODO 3: days_overdue."""

    # 95 days against a 14 day limit is 81 days late.
    def test_overdue_host(self) -> None:
        self.assertEqual(pa.days_overdue(95, 3), 81)

    # A host inside its limit is 0 days late, never a negative number.
    def test_on_time_host_is_zero(self) -> None:
        self.assertEqual(pa.days_overdue(9, 3), 0)

    # Exactly on the limit is 0 days late.
    def test_exactly_on_the_limit_is_zero(self) -> None:
        self.assertEqual(pa.days_overdue(30, 2), 0)


class TestBuildStatuses(unittest.TestCase):
    """TODO 4: build_statuses."""

    # One status for every host.
    def test_one_status_per_host(self) -> None:
        statuses = pa.build_statuses(pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(len(statuses), 11)

    # The statuses stay in the same order as the hosts.
    def test_statuses_keep_their_order(self) -> None:
        statuses = pa.build_statuses(pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(statuses[:3], ["COMPLIANT", "CRITICAL", "COMPLIANT"])

    # The last host is on the exception list.
    def test_last_host_is_exempt(self) -> None:
        statuses = pa.build_statuses(pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(statuses[-1], "EXEMPT")


class TestCountStatus(unittest.TestCase):
    """TODO 5: count_status."""

    # Two of the three are OVERDUE.
    def test_counts_matches(self) -> None:
        self.assertEqual(pa.count_status(["OVERDUE", "COMPLIANT", "OVERDUE"], "OVERDUE"), 2)

    # No match gives 0.
    def test_no_match_is_zero(self) -> None:
        self.assertEqual(pa.count_status(["COMPLIANT"], "CRITICAL"), 0)


class TestHostsWithStatus(unittest.TestCase):
    """TODO 6: hosts_with_status."""

    # Only the hosts whose status matches, in their original order.
    def test_matching_hosts(self) -> None:
        self.assertEqual(pa.hosts_with_status(["a", "b", "c"], ["CRITICAL", "COMPLIANT", "CRITICAL"], "CRITICAL"),
                         ["a", "c"])

    # No match gives an empty list.
    def test_no_match(self) -> None:
        self.assertEqual(pa.hosts_with_status(["a"], ["COMPLIANT"], "CRITICAL"), [])


class TestAverageDays(unittest.TestCase):
    """TODO 7: average_days, the function that is finished and wrong."""

    # Two hosts, both counted: (10 + 20) / 2 = 15.0. A loop that starts at 1
    # skips the first host.
    def test_the_first_host_is_counted(self) -> None:
        self.assertEqual(pa.average_days([10, 20], ["COMPLIANT", "COMPLIANT"]), 15.0)

    # EXEMPT hosts are left out: (10 + 20) / 2 = 15.0, not (10 + 20 + 999) / 3.
    def test_exempt_is_left_out(self) -> None:
        self.assertEqual(pa.average_days([10, 20, 999], ["COMPLIANT", "OVERDUE", "EXEMPT"]), 15.0)

    # The whole inventory: 471 days over 9 audited hosts.
    def test_whole_inventory(self) -> None:
        statuses = pa.build_statuses(pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(pa.average_days(pa.DAYS_SINCE_PATCH, statuses), 52.3)


if __name__ == "__main__":
    unittest.main(verbosity=2)
